import { registerAs } from '@nestjs/config';
import { ConfigKey } from './enums';
import { TwitchConfig } from './types';

export default registerAs(
  ConfigKey.Twitch,
  (): TwitchConfig => ({
    client_id: process.env.TWITCH_CLIENT_ID,
    client_secret: process.env.TWITCH_CLIENT_SECRET,
    redirect_uri: process.env.TWITCH_REDIRECT_URL,
    response_type: 'code',
    grant_type: 'authorization_code',
    scope: [
      'channel:read:charity',
      'channel:read:polls',
      'channel:read:vips',
      'channel:read:hype_train',
      'channel:read:goals',
      'channel:read:editors',
      'channel:read:stream_key',
      'channel:read:subscriptions',
      'channel:read:predictions',
      'channel:read:redemptions',
      'channel:manage:broadcast',
      'channel:manage:moderators',
      'channel:manage:extensions',
      'channel:manage:polls',
      'channel:manage:vips',
      'channel:manage:predictions',
      'channel:manage:redemptions',
      'channel:manage:videos',
      'channel:manage:schedule',
      'channel:manage:raids',
      'channel:edit:commercial',
      'analytics:read:extensions',
      'analytics:read:games',
      'bits:read',
      'user:manage:whispers',
      'user:read:subscriptions',
      'user:read:follows',
      'user:read:email',
      'user:manage:chat_color',
      'user:read:broadcast',
      'user:read:blocked_users',
      'user:manage:blocked_users',
      'user:edit:follows',
      'user:edit',
      'clips:edit',
      'moderation:read',
      'moderator:read:chatters',
      'moderator:read:chat_settings',
      'moderator:read:blocked_terms',
      'moderator:read:automod_settings',
      'moderator:manage:chat_settings',
      'moderator:manage:chat_messages',
      'moderator:manage:blocked_terms',
      'moderator:manage:banned_users',
      'moderator:manage:automod_settings',
      'moderator:manage:automod',
      'moderator:manage:announcements',
    ]
      .map((scope) => scope.replace(':', '%3A'))
      .join('+'),
  }),
);
